# Generated by Django 5.2.8 on 2025-11-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Cím')),
                ('description', models.TextField(blank=True, verbose_name='Leírás')),
                ('priority', models.CharField(choices=[('low', 'Alacsony'), ('medium', 'Közepes'), ('high', 'Magas')], default='medium', max_length=10, verbose_name='Prioritás')),
                ('status', models.CharField(choices=[('todo', 'Tennivaló'), ('inprogress', 'Folyamatban'), ('done', 'Kész')], default='todo', max_length=20, verbose_name='Státusz')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Határidő')),
                ('createdat', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva')),
                ('updatedat', models.DateTimeField(auto_now=True, verbose_name='Módosítva')),
            ],
            options={
                'verbose_name': 'Feladat',
                'verbose_name_plural': 'Feladatok',
            },
        ),
    ]
