# Generated by Django 5.2.8 on 2025-11-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-createdat'], 'verbose_name': 'Feladat', 'verbose_name_plural': 'Feladatok'},
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'Tennivaló'), ('in_progress', 'Folyamatban'), ('done', 'Kész')], default='todo', max_length=20, verbose_name='Státusz'),
        ),
    ]
